apiVersion: apps/v1

kind: Deployment

metadata:

  name: gateway-deployment

  labels:

    app: gateway

spec:

  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge : 3
      maxUnavailable : 1

  selector:
    matchLabels:
      app: gateway

  template:

    metadata:
      labels:
        app: gateway

    spec:
        containers:
        - name: gateway
        image: abdelrhmanhamdy/gateway
        ports:
        - containerPort: 8080
        envFrom :
          configMapRef :
            name:  gateway-config