apiVersion: apps/v1

kind: Deployment

metadata:
  name: Deployment-auth
  labels: 
    app : auth 

spec:

  selector:
    matchLabels:
      app: auth
  
  template:
    metadata:
      labels:
        app: auth

  replicas: 2

  strategy:
      type: RollingUpdate
      maxSurge: 3
      maxUnavailable: 1
  spec:
    containers:
    - name: auth
      image: abdelrhmanhamdy/auth
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
      - containerPort: 5000
    - envFrom: 
      - configMapRef :
        name : auth-configmap
      - secretRef:
        name: auth-secret