apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq 
  type: ClusterIP
  ports:
  - port: 15672
    name : http 
    targetPort: 15672

    protocol: TCP
  - port: 5672
    name : amqp
    targetPort: 5672
    protocol: TCP